################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_CORE "biosapi")
    if (NOT PC_CORE_FOUND)
        pkg_check_modules(PC_CORE "biosapi")
    endif (NOT PC_CORE_FOUND)
    if (PC_CORE_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_CORE_CFLAGS} ${PC_CORE_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_CORE_INCLUDE_HINTS ${PC_CORE_INCLUDE_DIRS} ${PC_CORE_INCLUDE_DIRS}/*)
        set(PC_CORE_LIBRARY_HINTS ${PC_CORE_LIBRARY_DIRS} ${PC_CORE_LIBRARY_DIRS}/*)
    endif(PC_CORE_FOUND)
endif (NOT MSVC)

find_path (
    CORE_INCLUDE_DIRS
    NAMES biosapi.h
    HINTS ${PC_CORE_INCLUDE_HINTS}
)

find_library (
    CORE_LIBRARIES
    NAMES biosapi
    HINTS ${PC_CORE_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    CORE
    REQUIRED_VARS CORE_LIBRARIES CORE_INCLUDE_DIRS
)
mark_as_advanced(
    CORE_FOUND
    CORE_LIBRARIES CORE_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
