/*  =========================================================================
    fty_asset_classes - private header file

    Copyright (C) 2014 - 2018 Eaton

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef FTY_ASSET_CLASSES_H_INCLUDED
#define FTY_ASSET_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/fty-asset.h"

//  Opaque class structures to allow forward references
#ifndef TOPOLOGY_POWER_PERSIST_DBHELPERS2_T_DEFINED
typedef struct _topology_power_persist_dbhelpers2_t topology_power_persist_dbhelpers2_t;
#define TOPOLOGY_POWER_PERSIST_DBHELPERS2_T_DEFINED
#endif
#ifndef TOPOLOGY_POWER_PERSIST_ASSETCRUD_T_DEFINED
typedef struct _topology_power_persist_assetcrud_t topology_power_persist_assetcrud_t;
#define TOPOLOGY_POWER_PERSIST_ASSETCRUD_T_DEFINED
#endif
#ifndef TOPOLOGY_POWER_PERSIST_ASSETTOPOLOGY_T_DEFINED
typedef struct _topology_power_persist_assettopology_t topology_power_persist_assettopology_t;
#define TOPOLOGY_POWER_PERSIST_ASSETTOPOLOGY_T_DEFINED
#endif
#ifndef TOPOLOGY_POWER_PERSIST_MONITOR_T_DEFINED
typedef struct _topology_power_persist_monitor_t topology_power_persist_monitor_t;
#define TOPOLOGY_POWER_PERSIST_MONITOR_T_DEFINED
#endif
#ifndef TOPOLOGY_POWER_PERSIST_PERSIST_ERROR_T_DEFINED
typedef struct _topology_power_persist_persist_error_t topology_power_persist_persist_error_t;
#define TOPOLOGY_POWER_PERSIST_PERSIST_ERROR_T_DEFINED
#endif
#ifndef TOPOLOGY_POWER_SHARED_UTILSPP_T_DEFINED
typedef struct _topology_power_shared_utilspp_t topology_power_shared_utilspp_t;
#define TOPOLOGY_POWER_SHARED_UTILSPP_T_DEFINED
#endif
#ifndef TOPOLOGY_POWER_MSG_ASSET_MSG_T_DEFINED
typedef struct _topology_power_msg_asset_msg_t topology_power_msg_asset_msg_t;
#define TOPOLOGY_POWER_MSG_ASSET_MSG_T_DEFINED
#endif
#ifndef TOPOLOGY_POWER_MSG_COMMON_MSG_T_DEFINED
typedef struct _topology_power_msg_common_msg_t topology_power_msg_common_msg_t;
#define TOPOLOGY_POWER_MSG_COMMON_MSG_T_DEFINED
#endif
#ifndef TOPOLOGY_POWER_TOPOLOGY_POWER_T_DEFINED
typedef struct _topology_power_topology_power_t topology_power_topology_power_t;
#define TOPOLOGY_POWER_TOPOLOGY_POWER_T_DEFINED
#endif
#ifndef TOPOLOGY_POWER_PROCESSOR_T_DEFINED
typedef struct _topology_power_processor_t topology_power_processor_t;
#define TOPOLOGY_POWER_PROCESSOR_T_DEFINED
#endif
#ifndef DBHELPERS_T_DEFINED
typedef struct _dbhelpers_t dbhelpers_t;
#define DBHELPERS_T_DEFINED
#endif
#ifndef TOTAL_POWER_T_DEFINED
typedef struct _total_power_t total_power_t;
#define TOTAL_POWER_T_DEFINED
#endif
#ifndef DNS_T_DEFINED
typedef struct _dns_t dns_t;
#define DNS_T_DEFINED
#endif

//  Extra headers
#include "topology_power/dbtypes.h"
#include "topology_power/cleanup.h"

//  Internal API

#include "topology_power/persist/dbhelpers2.h"
#include "topology_power/persist/assetcrud.h"
#include "topology_power/persist/assettopology.h"
#include "topology_power/persist/monitor.h"
#include "topology_power/persist/persist_error.h"
#include "topology_power/shared/utilspp.h"
#include "topology_power/msg/asset_msg.h"
#include "topology_power/msg/common_msg.h"
#include "topology_power/topology_power.h"
#include "topology_power_processor.h"
#include "dbhelpers.h"
#include "total_power.h"
#include "dns.h"

//  *** To avoid double-definitions, only define if building without draft ***
#ifndef FTY_ASSET_BUILD_DRAFT_API

//  Self test for private classes
FTY_ASSET_PRIVATE void
    fty_asset_private_selftest (bool verbose, const char *subtest);

#endif // FTY_ASSET_BUILD_DRAFT_API

#endif
